### ISSUE TITLE
Grading Queue form: Keep the Sorting Direction

### ISSUE THREAD

**Issue by GeorgeRay** [GeorgeRay/DavisTechCanvasAPIApp#21]
When the grading queue refreshes it changes the sorting.  Keep the sorting the user is currently using.

**Comment by cheeseonamonkey** [comment]
Its tricky to understand some of the issues when I don't have anything teacher-related to populate the forms, specifically the grading queue form for this issue.

Its about time to turn in team activity and module completion reports anyway, so I'll see what I can do on this issue this weekend while there are a couple things there visible to me.

**Comment by TheGeorgeRay** [comment]
The priority sort does not work unless there is a 3 or lower in the the queue. This needs fixed, but we need to write up a use case.

**Comment by GeorgeRay** [comment]
I think, on refresh, we should sort by the priority and then submission date and leave it at that.
________________________________
