### ISSUE TITLE
Crash when entering invalid access token/student access token

### ISSUE THREAD

**Issue by cheeseonamonkey** [GeorgeRay/DavisTechCanvasAPIApp#27]
Whole program is crashing when closing/submitting the AccessTokenForm with an invalid token.

This will happen with a token without teacher privileges as well.

If an invalid URL or access token is entered it is possible to get stuck in an _instant crash upon opening_ the program, because it isn't offering the AccessTokenForm dialog to let you modify the access token or URL if they are invalid, only if they are default. To amend this for testing I had to go into local AppData and set the access token back to the default of "No access token"

**Comment by GeorgeRay** [comment]
The WebRequest is throwing an error in the WebCall Class. I added a try-catch as a temporary solution. We need to figure out a way to catch and handle the 401 error appropriately.  The MS docs say not to use WebRequest.  I wonder if the HttpClient the docs suggests would be a better solution. I am going to close this issue and open a new one to try the HttpClient Class.
