### ISSUE TITLE
Add HttpClient library to project to replace WebRequest library

### ISSUE THREAD

**Issue by GeorgeRay** [GeorgeRay/DavisTechCanvasAPIApp#29]

**Comment by cheeseonamonkey** [comment]
I was looking at this today and the current WebCall class is set up in such a way that it will be very easy to upgrade to HttpClient. The request method only return a JSON string to every call, so it shouldn't require changes in any other class.

I am pretty comfortable with HttpClient already, I want to start on this once we get a pretty stable build.
