### ISSUE TITLE
Grading Queue: Bring the app in focus if there is a priority assignment

### ISSUE THREAD

**Issue by GeorgeRay** [GeorgeRay/DavisTechCanvasAPIApp#5]

**Comment by cheeseonamonkey** [comment]
I'm thinking that the same settings form that priorities are set in would be a good place for the user to set this.

We'd definitely want the user to be able to enable/disable this, and to determine themselves what priority level determines a 'priority assignment.'

**Comment by GeorgeRay** [comment]
We talked about adding the option of a check box to the priority to bring the app into focus.
